### PR TITLE
`coreLint`: Fix checking of newtype update expressions

### LINKED ISSUE #2025: `coreLint` panics on newtype record update
`coreLint` has no issues checking updates on record values, e.g.,

```
type R = { getR : [8] }

r1 : R
r1 = { getR = 27 }

r2 : R
r2 = { r1 | getR = 42 }
```

On the other hand, `coreLint` will panic if given an update on a newtype value, e.g.,

```
// Bug.cry

newtype N = { getN : [8] }

n1 : N
n1 = N { getN = 27 }

n2 : N
n2 = { n1 | getN = 42 }
```
```
$ ~/Software/cryptol-3.5.0/bin/cryptol -c ":set coreLint=on" -c ":load Bug.cry"
Loading module Cryptol
Loading module Cryptol
{n, a, b, c} n == min n n
{a, n} (fin n) => inf == inf * (1 * (1 * 1))
{a, n} (fin n) => n / 2 + n /^ 2 == n
{n, a, b} n == min n n
{n} (n >= 1, fin n) => (fin n, n >= 1)
Loading module Main
cryptol: You have encountered a bug in Cryptol's implementation.
*** Please create an issue at https://github.com/GaloisInc/cryptol/issues

%< ---------------------------------------------------
  Revision:  6173b60ad40822a1563ea4f569b04a70806b67fd
  Branch:    release-3.5.0 (uncommited files present)
  Location:  Core lint failed:
  Message:   Location: Bug.cry:9:6--9:24
             Bad selector
  • Selector: getN
  • Type    : Main::N
CallStack (from HasCallStack):
  panic, called at src/Cryptol/Utils/Panic.hs:21:9 in cryptol-3.5.0-inplace:Cryptol.Utils.Panic
  panic, called at src/Cryptol/ModuleSystem/Base.hs:785:29 in cryptol-3.5.0-inplace:Cryptol.ModuleSystem.Base
%< ---------------------------------------------------
```

### PR DESCRIPTION
**Pull request by RyanGlScott**
The `coreLint` implementation previously assumed that record update syntax could only occur on record values, but they can also occur on newtype values. As such, `coreLint` would panic if it encountered a record update on a newtype. This commit fixes the issue by adding a new case under `RecordSel` for newtypes.

Fixes https://github.com/GaloisInc/cryptol/issues/2025.

### CODE REVIEW

File: src/Cryptol/TypeCheck/Sanity.hs [hunk 1]
```diff
@@ -394,39 +394,19 @@ checkHas t sel =
              unless (n < sz) $ reportError (TupleSelectorOutOfRange n sz)
              return $ ts !! n
 
-        TCon (TC TCSeq) [s,elT] ->
```
Comment (yav) [inline src/Cryptol/TypeCheck/Sanity.hs:397]: Did we remove these, because they should have been desugared away by now?

**Review by yav — APPROVED** [review]

File: src/Cryptol/TypeCheck/Sanity.hs (hunk 1 above)
Comment (RyanGlScott) [reply src/Cryptol/TypeCheck/Sanity.hs:397]: Yes. See the commit message in https://github.com/GaloisInc/cryptol/pull/2026/commits/60693267f7b51cd02d631bc456b2676373d4a88a for details.
