### PR TITLE
Doctest support for Python API

### LINKED ISSUE #1865: Loading projects from the Python API does not work correctly
There's a few issues that prevent running doctests from the Cryptol API, namely:
  * The names of the scanned modules are incorrect, making it impossible to test them
  * There's a bug in loading projects that prevents us from finding the file (see #1832)
  * We produce too much output for testing commands (we don't need the progress bar output)
  * We don't have a good example of how to run doctests with the Python API

### PR DESCRIPTION
**Pull request by yav**
Fixes #1865, #1832

This PR contains a collection of fixes to the support for running docstings tests from the Python API, using projects and caching.  Besides the bugfixes, the PR adds a detailed Python script with an example of how to use the API to run tests with caching.

### CODE REVIEW

**Comment by weaversa** [comment]
@yav Would you be willing to throw [junit xml](https://pypi.org/project/junitxml/) into your example script, to support CI results?

File: cryptol-remote-api/src/CryptolServer/Utils.hs [hunk 1]
```diff
@@ -0,0 +1,51 @@
...
+
+import Data.Text(Text)
+import qualified Data.Text as Text
+import qualified Data.ByteString as BS
+import Data.Word
+import Data.Bits
+
+import Data.Aeson
+
+newtype BS = BS BS.ByteString
```
Comment (RyanGlScott) [inline cryptol-remote-api/src/CryptolServer/Utils.hs:11]: What is this type? Why do we need it separately from `ByteString`? Including some Haddocks would be helpful.
