### PR TITLE
Issue851

### LINKED ISSUE #851: type mismatch in Cryptol.Eval.Concrete.toExpr
In this spec

    type base t = { zero: t }

    B: base Bool
    B = { zero = False }

    foo: {t,k} (fin k) => base t -> [k]t
    foo B = repeat B.zero

    bar: {t,k} (fin k, k>=1) => [k]t -> [k]t -> [k]t -> [k]t
    bar p q m = p

    baz: {k,t} (fin k, k >= 1) => [k]t -> [k]t -> [k]t
    baz p q = q

    property problem p =
      p != foo B ==> bar p (baz p 0x03) 0x03 == foo B

running `:check problem` crashes Cryptol:

    Main> :check problem 
    Using random testing.
    problem 0x82 = False
    cryptol: You have encountered a bug in Cryptol's implementation.
    *** Please create an issue at https://github.com/GaloisInc/cryptol/issues

    %< --------------------------------------------------- 
      Revision:  c53f3cf1723235ad6b428e8b7be6b752823767a7
      Branch:    HEAD
      Location:  Cryptol.Eval.Concrete.toExpr
      Message:   type mismatch:
                 [8]Cryptol::Bool
                 130
    CallStack (from HasCallStack):
      panic, called at src/Cryptol/Utils/Panic.hs:21:9 in cryptol-2.9.0-IwOb2yTO6mD35k7fNx79Kk:Cryptol.Utils.Panic
      panic, called at src/Cryptol/Eval/Concrete.hs:99:13 in cryptol-2.9.0-IwOb2yTO6mD35k7fNx79Kk:Cryptol.Eval.Concrete
    %< ---------------------------------------------------

### PR DESCRIPTION
**Pull request by brianhuffman**
Rewrite function `toExpr` using a complete pattern match.

Fixes #851.

I'm still a little unsure about where exactly we should be using `panic` in this function, and where we should be using `fail`/`guard`/`mzero`.

### CODE REVIEW

File: src/Cryptol/Eval/Concrete.hs [hunk 1]
```diff
@@ -65,45 +63,47 @@ toExpr prims t0 v0 = findOne (go t0 v0)
...
-    (TCon (TC TCIntMod) [_n], VInteger i) ->
-      return $ ETApp (ETApp (prim "number") (tNum i)) ty
-    (TCon (TC TCRational) [], VRational (SRational n d)) ->
-      do let n' = ETApp (ETApp (prim "number") (tNum n)) (TCon (TC TCInteger) [])
-             d' = ETApp (ETApp (prim "number") (tNum d)) (TCon (TC TCInteger) [])
-         return $ EApp (EApp (prim "ratio") n') d'
-    (TCon (TC TCFloat) [eT,pT], VFloat i) ->
-      pure (floatToExpr prims eT pT (bfValue i))
-
-    (TCon (TC TCSeq) [a,b], VSeq 0 _) -> do
```
Comment (robdockins) [inline src/Cryptol/Eval/Concrete.hs:91]: Weird that this special case is here... it seems unnecessary, but do we know why it is here?

Comment (brianhuffman) [reply src/Cryptol/Eval/Concrete.hs:91]: It looked to me like that special case was completely redundant; I'm not sure why it was there.

Comment (robdockins) [reply src/Cryptol/Eval/Concrete.hs:91]: Looks like that code has been bouncing around with that special case since 156771a5d5fe405d7e033928a1ac25d43ebf3642.  Dosen't seem like there's a specific reason. *shrug*
